### ISSUE TITLE
To contribute or to fork

### ISSUE THREAD

**Issue by miljan-aleksic** [lucasmotta/dploy#103]
@lucasmotta, I was playing around with the new beta version and after fixing few bugs seems working quite fine. I am willing to contribute and help pushing forward this project but doesn't seem you have the time to manage it. Should I fork it, instead?

**Comment by lucasmotta** [comment]
Hey @miljan-aleksic, thanks so much for stepping up! I haven't had the time to maintain dploy and I know it has been very useful to a lot of people. I've added you as a collaborator so you can push the development further! Thank you again!

**Comment by miljan-aleksic** [comment]
Well, that's something :)

@lucasmotta, should I prepare a small milestone, that should be reviewed by you, keep you on top of the progress, etc? For example, I would drop babel integration and rise up node version to the one that supports ES6 natively (we only have to convert the imports to the old way).

**Comment by lucasmotta** [comment]
@miljan-aleksic sounds like a great idea! I did some changes recently which I didn't push yet - some refactoring and adding stronger linting rules. If you haven't done any work yet, I can push this first and then you can start from there?

**Comment by miljan-aleksic** [comment]
Do so, please! As stronger linting rules was among the priorities :)
