### ISSUE TITLE
Strategy for deploying from build directory without tracking it

### ISSUE THREAD

**Issue by MarkLeMerise** [lucasmotta/dploy#45]
Right now, I have a pretty basic folder structure for my app:

```
| myapp
    |--www
    |--deploy
    |--dploy.yaml
    |--buildfile
```

When I run a build process, it builds into the `deploy` folder, which I have also set in `.gitignore`. I have added `www` to the `exclude` array in `dploy.yaml`.

With this setup, DPLOY will only want to upload the `.rev` file and nothing else. Ideally, I would like to keep the `deploy` directory ignored as it adds a lot of weight to the repo if tracked. Is there a prescribed strategy for this type of situation?

**Comment by lucasmotta** [comment]
I'm happy to say that the new dploy will have a new `map` parameter, which will allow you to upload the files that are not being tracked by Git!
Have a look at this discussion: #72 - the new version of dploy will be pushed to npm at some point next week!
