### ISSUE TITLE
path wrong

### ISSUE THREAD

**Issue by xavierartot** [lucasmotta/dploy#85]
Hi,

My config:

`server_dev:

```
host: "ftp.artot.net"

user: "artot.net"

pass: ""

path:

  remote: "test/"
```

exclude: ["dploy.yaml", "package.json", ".gitignore", "*.md", "bower_components", "node_modules", ".DS_Store"]`

the file are look good:

......a lot of file like this...
[ + ] File uploaded: templates/head.php:

[ + ] File uploaded: templates/header.php:

[ + ] File uploaded: templates/page-header.php:

[ + ] File uploaded: templates/sidebar.php:

[ + ] File uploaded: third-party-libraries:

[ + ] File uploaded: variable-less:

[ + ] File uploaded: widget-recent-post.php:

[ + ] File uploaded: .rev:

Upload completed for server_dev
All Completed :)

but they not in the server?

Thank you

**Comment by miton18** [comment]
have you modifie this files?

**Comment by xavierartot** [comment]
dploy.yaml ?

**Comment by miton18** [comment]
files who aren't in server,  If you Don t change file they aren't upload again. and if you had a problem the first time, that 's why they aren't upload

**Comment by xavierartot** [comment]
Even if the .rev is not in the server?

**Comment by miton18** [comment]
have you any file uploaded on your server?

**Comment by xavierartot** [comment]
yes, in a different folder: crateplus/wp-content/theme/sage/
But I try to push here: test/

**Comment by miton18** [comment]
can you put a test file on test/ with an ftp client? like filezilla  to check if you have good rights?

**Comment by xavierartot** [comment]
I re-dploy install and it works now.
