### ISSUE TITLE
Dploy stop after transfert 1 file

### ISSUE THREAD

**Issue by souhailmerroun** [lucasmotta/dploy#93]
Dploy upload my .htaccess and then stops, i get no warning no nothing. 
![image 2](https://cloud.githubusercontent.com/assets/8895242/13927825/37d6efae-ef8b-11e5-9e05-7657cb9a55c0.png)

**Comment by LeG3nDz** [comment]
+1

**Comment by souhailmerroun** [comment]
@LeG3nDz Hey, bro it seems that no one is here for issues, try to move on to some services like [http://deployhq.com/](url)
