### ISSUE TITLE
Exclude directories

### ISSUE THREAD

**Issue by standingdreams** [lucasmotta/dploy#97]
I see how to exclude files but I have not seen a clear cut way to exclude an entire directory from deploying.

**Comment by jonahcoyote** [comment]
I would also like to be able to do this. Thanks!

**Comment by jonahcoyote** [comment]
As soon as I posted that I figured out how to do it, just use: "directory_name/**" and it will exclude the entire directory!

**Comment by standingdreams** [comment]
Thank you @jonahcoyote. That was exactly what I needed!
